/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.moviemanagement.GUI;

import com.mycompany.moviemanagement.Models.Movie;
import com.mycompany.moviemanagement.Models.WatchedMovie;
import com.mycompany.moviemanagement.Repositories.MovieDAO;
import com.mycompany.moviemanagement.Repositories.MovieDAOImp;
import com.mycompany.moviemanagement.Repositories.UserDAO;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author nhath
 */
public class Index extends javax.swing.JFrame {
    
    /** 
     * Creates new form Index
     * @param userDao
     */
    public Index(UserDAO userDao) {
        movieDao = new MovieDAOImp();
        this.userDao = userDao;
        initComponents();
        jTFUsername.setText(this.userDao.getUsername());
        List<Movie> movies = movieDao.getAllMovies();
        generateMoviePanels(movies);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanelContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneHeader = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        jTFUsername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnShowFavorites = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnShowWatchedMovies = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnInsertMovie = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jTFSearch = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBtnLogout = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBtnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movies");

        jPanelContainer.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        jScrollPane.setViewportView(jPanelContainer);

        jTextPaneHeader.setEditable(false);
        jTextPaneHeader.setBackground(new java.awt.Color(240, 240, 240));
        jTextPaneHeader.setBorder(null);
        jTextPaneHeader.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextPaneHeader.setText("Movies List");
        jTextPaneHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPaneHeader.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(jTextPaneHeader);

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setForeground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jTFUsername.setEditable(false);
        jTFUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTFUsername.setText("jTextField2");
        jToolBar1.add(jTFUsername);
        jToolBar1.add(jSeparator3);

        jBtnShowFavorites.setBackground(new java.awt.Color(255, 255, 255));
        jBtnShowFavorites.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnShowFavorites.setText("Favorites");
        jBtnShowFavorites.setFocusable(false);
        jBtnShowFavorites.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnShowFavorites.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnShowFavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowFavoritesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnShowFavorites);
        jToolBar1.add(jSeparator1);

        jBtnShowWatchedMovies.setBackground(new java.awt.Color(255, 255, 255));
        jBtnShowWatchedMovies.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnShowWatchedMovies.setText("Watched movies");
        jBtnShowWatchedMovies.setFocusable(false);
        jBtnShowWatchedMovies.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnShowWatchedMovies.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnShowWatchedMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowWatchedMoviesActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnShowWatchedMovies);
        jToolBar1.add(jSeparator2);

        jBtnInsertMovie.setBackground(new java.awt.Color(255, 255, 255));
        jBtnInsertMovie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnInsertMovie.setText("+ New movie");
        jBtnInsertMovie.setFocusable(false);
        jBtnInsertMovie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnInsertMovie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnInsertMovie.setEnabled(userDao.isAdmin());
        jBtnInsertMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertMovieActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnInsertMovie);
        jToolBar1.add(jSeparator4);

        jTFSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFSearch.setText("Press Enter to search");
        jTFSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSearchKeyPressed(evt);
            }
        });
        jToolBar1.add(jTFSearch);
        jToolBar1.add(jSeparator6);

        jBtnLogout.setBackground(new java.awt.Color(255, 255, 255));
        jBtnLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnLogout.setText("Log out");
        jBtnLogout.setFocusable(false);
        jBtnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnLogout);
        jToolBar1.add(jSeparator5);

        jBtnRefresh.setText("Refresh");
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnShowFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowFavoritesActionPerformed
        // TODO add your handling code here:
        List<Movie> m = userDao.getUserWishlist();
//        FavoritesFrame frame = new FavoritesFrame(m, userDao);
//        frame.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FavoritesFrame(m, userDao).setVisible(true);
            }
        });
    }//GEN-LAST:event_jBtnShowFavoritesActionPerformed

    private void jBtnShowWatchedMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowWatchedMoviesActionPerformed
        // TODO add your handling code here:
        List<WatchedMovie> m = userDao.getUserWatchedMovies();
//        WatchedMoviesFrame frame = new WatchedMoviesFrame(m, userDao);
//        frame.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WatchedMoviesFrame(m, userDao).setVisible(true);
            }
        });
    }//GEN-LAST:event_jBtnShowWatchedMoviesActionPerformed

    private void jBtnInsertMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertMovieActionPerformed
        // TODO add your handling code here:
        InsertFrame frame = new InsertFrame();
        frame.setVisible(true);
        
        if(!frame.isDisplayable()) {
            List<Movie> newMovies = movieDao.getAllMovies();
            generateMoviePanels(newMovies);
        }
    }//GEN-LAST:event_jBtnInsertMovieActionPerformed

    private void jTFSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String text = jTFSearch.getText();
            if(text.isBlank()) {
                List<Movie> movies = movieDao.getAllMovies();
                generateMoviePanels(movies);
            }
            List<Movie> movies = movieDao.search(text);
            generateMoviePanels(movies);
            
        }
    }//GEN-LAST:event_jTFSearchKeyPressed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        // TODO add your handling code here:
        userDao.logout();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
        List<Movie> movies = movieDao.getAllMovies();
        generateMoviePanels(movies);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void generateMoviePanels(List<Movie> movies) {   
        this.jPanelContainer.removeAll();
        
        movies.forEach(m -> {
            MoviePanel moviePanel = new MoviePanel(m, userDao);
            moviePanel.setPreferredSize(new Dimension(200,300));
            this.jPanelContainer.add(moviePanel);
        });
        this.validate();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Index(new User(2, "jdiego", "123456", "admin")).setVisible(true);
//            }
//        });
//    }
    
    MovieDAO movieDao;
    UserDAO userDao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInsertMovie;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnShowFavorites;
    private javax.swing.JButton jBtnShowWatchedMovies;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTextField jTFSearch;
    private javax.swing.JTextField jTFUsername;
    private javax.swing.JTextPane jTextPaneHeader;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
