/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.moviemanagement.GUI;

import com.mycompany.moviemanagement.Models.Credit;
import com.mycompany.moviemanagement.Models.Movie;
import com.mycompany.moviemanagement.Models.ReleaseDate;
import com.mycompany.moviemanagement.Models.UserResponse;
import com.mycompany.moviemanagement.Repositories.MovieDAO;
import com.mycompany.moviemanagement.Repositories.MovieDAOImp;
import com.mycompany.moviemanagement.Repositories.UserDAO;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPopupMenu;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nhath
 */
public class InsertFrame extends java.awt.Frame {
    
    /**
     * Creates new form MovieInfoFrame
     */
    public InsertFrame() {
        this.movieDao = new MovieDAOImp();
        creditsTableModel = new DefaultTableModel(new String[] {"Name", "Gender", "Type", "Chacracter", "Position"}, 0);        
        releaseDatesTableModel = new DefaultTableModel(new String[] {"Release date", "Country"}, 0);
        languagesListModel = new DefaultListModel();
        locationsListModel = new DefaultListModel();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbTitle = new javax.swing.JLabel();
        jLbGenres = new javax.swing.JLabel();
        jLbReleaseDate = new javax.swing.JLabel();
        jLbLanguages = new javax.swing.JLabel();
        jLbCredits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCredits = new javax.swing.JTable();
        jLbLocations = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLocations = new javax.swing.JList<>();
        jLbRunningTimes = new javax.swing.JLabel();
        jLbKeywords = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextKeywords = new javax.swing.JTextArea();
        jBtnFinish = new javax.swing.JButton();
        jBtnInsertFromFile = new javax.swing.JButton();
        jTFTitle = new javax.swing.JTextField();
        jTFRunningtime = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAreaGenres = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListLanguages = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableReleaseDates = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanelLocationInfo = new javax.swing.JPanel();
        jLbTitle_locationPanel = new javax.swing.JLabel();
        jTFLocation_locationPanel = new javax.swing.JTextField();
        jBtnRemove_locationPanel = new javax.swing.JButton();
        jBtnNew_locationPanel = new javax.swing.JButton();
        jBtnSave_locationPanel = new javax.swing.JButton();
        jPanelLanguageInfo = new javax.swing.JPanel();
        jLbTitle_languagePanel = new javax.swing.JLabel();
        jTFLanguage_languagePanel = new javax.swing.JTextField();
        jBtnRemove_languagePanel = new javax.swing.JButton();
        jBtnNew_languagePanel = new javax.swing.JButton();
        jBtnSave_languagePanel = new javax.swing.JButton();
        jPanelReleaseDate = new javax.swing.JPanel();
        jLbTitle_relDatePanel = new javax.swing.JLabel();
        jLbDate_relDatePanel = new javax.swing.JLabel();
        jTFDate_relDatePanel = new javax.swing.JTextField();
        jTFCountry_relDatePanel = new javax.swing.JTextField();
        jLbCountry_relDatePanel = new javax.swing.JLabel();
        jBtnRemove_relDatePanel = new javax.swing.JButton();
        jBtnNew_relDatePanel = new javax.swing.JButton();
        jBtnSave_relDatePanel = new javax.swing.JButton();
        jPanelCreditInfo = new javax.swing.JPanel();
        jLbTitle_creditPanel = new javax.swing.JLabel();
        jLbName_creditPanel = new javax.swing.JLabel();
        jTFName_creditPanel = new javax.swing.JTextField();
        jTFGender_creditPanel = new javax.swing.JTextField();
        jLbGender_creditPanel = new javax.swing.JLabel();
        jLbType_creditPanel = new javax.swing.JLabel();
        jTFType_creditPanel = new javax.swing.JTextField();
        jLbCharacter_creditPanel = new javax.swing.JLabel();
        jTFCharacter_creditPanel = new javax.swing.JTextField();
        jLbPosition_creditPanel = new javax.swing.JLabel();
        jTFPosition_creditPanel = new javax.swing.JTextField();
        jBtnSave_creditPanel = new javax.swing.JButton();
        jBtnRemove_creditPanel = new javax.swing.JButton();
        jBtnNew_creditPanel = new javax.swing.JButton();
        jBtnNextCrad = new javax.swing.JButton();
        jBtnPrevCard = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setToolTipText("Info");
        jPanel1.setPreferredSize(new java.awt.Dimension(764, 1000));

        jLbTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbTitle.setText("Title:");

        jLbGenres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbGenres.setText("Genres:");

        jLbReleaseDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbReleaseDate.setText("Running times:");

        jLbLanguages.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbLanguages.setText("Languages:");

        jLbCredits.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbCredits.setText("Stars:");

        jTableCredits.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTableCredits.setModel(creditsTableModel);
        jTableCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCreditsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCredits);

        jLbLocations.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbLocations.setText("Locations:");

        jListLocations.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jListLocations.setModel(locationsListModel);
        jListLocations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLocationsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListLocations);

        jLbRunningTimes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbRunningTimes.setText("Release dates");

        jLbKeywords.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbKeywords.setText("Keywords:");

        jTextKeywords.setColumns(20);
        jTextKeywords.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextKeywords.setRows(5);
        jScrollPane3.setViewportView(jTextKeywords);

        jBtnFinish.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnFinish.setText("Done");
        jBtnFinish.setToolTipText("");
        jBtnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinishActionPerformed(evt);
            }
        });

        jBtnInsertFromFile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnInsertFromFile.setText("Insert from file");
        jBtnInsertFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertFromFileActionPerformed(evt);
            }
        });

        jTFTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTAreaGenres.setColumns(20);
        jTAreaGenres.setRows(5);
        jScrollPane4.setViewportView(jTAreaGenres);

        jListLanguages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListLanguages.setModel(languagesListModel);
        jListLanguages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLanguagesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListLanguages);

        jTableReleaseDates.setModel(releaseDatesTableModel);
        jTableReleaseDates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReleaseDatesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableReleaseDates);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbTitle)
                    .addComponent(jLbReleaseDate)
                    .addComponent(jLbGenres)
                    .addComponent(jLbCredits)
                    .addComponent(jLbLocations)
                    .addComponent(jLbLanguages)
                    .addComponent(jLbRunningTimes)
                    .addComponent(jLbKeywords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnInsertFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFRunningtime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTitle)
                    .addComponent(jTFTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbReleaseDate)
                    .addComponent(jTFRunningtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbGenres)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbCredits))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbLanguages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbRunningTimes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbKeywords))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnInsertFromFile)
                    .addComponent(jBtnFinish))
                .addGap(443, 443, 443))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(290, 220));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLbTitle_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_locationPanel.setText("Location Info");

        jBtnRemove_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_locationPanel.setText("Remove");
        jBtnRemove_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_locationPanelActionPerformed(evt);
            }
        });

        jBtnNew_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_locationPanel.setText("New");
        jBtnNew_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_locationPanelActionPerformed(evt);
            }
        });

        jBtnSave_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_locationPanel.setText("Save");
        jBtnSave_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_locationPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLocationInfoLayout = new javax.swing.GroupLayout(jPanelLocationInfo);
        jPanelLocationInfo.setLayout(jPanelLocationInfoLayout);
        jPanelLocationInfoLayout.setHorizontalGroup(
            jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocationInfoLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addComponent(jLbTitle_locationPanel)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelLocationInfoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jBtnNew_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSave_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFLocation_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addComponent(jBtnRemove_locationPanel)
                        .addGap(100, 100, 100))))
        );
        jPanelLocationInfoLayout.setVerticalGroup(
            jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocationInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitle_locationPanel)
                .addGap(18, 18, 18)
                .addComponent(jTFLocation_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNew_locationPanel)
                    .addComponent(jBtnSave_locationPanel))
                .addGap(26, 26, 26)
                .addComponent(jBtnRemove_locationPanel)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelLocationInfo, "LocationCard");

        jLbTitle_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_languagePanel.setText("Language Info");

        jTFLanguage_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jBtnRemove_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_languagePanel.setText("Remove");
        jBtnRemove_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_languagePanelActionPerformed(evt);
            }
        });

        jBtnNew_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_languagePanel.setText("New");
        jBtnNew_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_languagePanelActionPerformed(evt);
            }
        });

        jBtnSave_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_languagePanel.setText("Save");
        jBtnSave_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_languagePanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLanguageInfoLayout = new javax.swing.GroupLayout(jPanelLanguageInfo);
        jPanelLanguageInfo.setLayout(jPanelLanguageInfoLayout);
        jPanelLanguageInfoLayout.setHorizontalGroup(
            jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLanguageInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbTitle_languagePanel)
                .addGap(124, 124, 124))
            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                        .addComponent(jBtnNew_languagePanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSave_languagePanel))
                    .addComponent(jTFLanguage_languagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                        .addComponent(jBtnRemove_languagePanel)
                        .addGap(35, 35, 35)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanelLanguageInfoLayout.setVerticalGroup(
            jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLbTitle_languagePanel)
                .addGap(18, 18, 18)
                .addComponent(jTFLanguage_languagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNew_languagePanel)
                    .addComponent(jBtnSave_languagePanel))
                .addGap(18, 18, 18)
                .addComponent(jBtnRemove_languagePanel)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelLanguageInfo, "languageCard");

        jLbTitle_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_relDatePanel.setText("Release Date Info");

        jLbDate_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbDate_relDatePanel.setText("Date");

        jTFDate_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTFCountry_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbCountry_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbCountry_relDatePanel.setText("Country");

        jBtnRemove_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_relDatePanel.setText("Remove");
        jBtnRemove_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_relDatePanelActionPerformed(evt);
            }
        });

        jBtnNew_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_relDatePanel.setText("New");
        jBtnNew_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_relDatePanelActionPerformed(evt);
            }
        });

        jBtnSave_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_relDatePanel.setText("Save");
        jBtnSave_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_relDatePanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReleaseDateLayout = new javax.swing.GroupLayout(jPanelReleaseDate);
        jPanelReleaseDate.setLayout(jPanelReleaseDateLayout);
        jPanelReleaseDateLayout.setHorizontalGroup(
            jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLbTitle_relDatePanel)
                .addGap(94, 94, 94))
            .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbDate_relDatePanel)
                    .addComponent(jLbCountry_relDatePanel))
                .addGap(18, 18, 18)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFDate_relDatePanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFCountry_relDatePanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                        .addComponent(jBtnSave_relDatePanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jBtnRemove_relDatePanel))
                    .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBtnNew_relDatePanel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReleaseDateLayout.setVerticalGroup(
            jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitle_relDatePanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbDate_relDatePanel)
                    .addComponent(jTFDate_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCountry_relDatePanel)
                    .addComponent(jTFCountry_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnNew_relDatePanel)
                .addGap(18, 18, 18)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRemove_relDatePanel)
                    .addComponent(jBtnSave_relDatePanel))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelReleaseDate, "RelDateCard");

        jPanelCreditInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanelCreditInfo.setPreferredSize(new java.awt.Dimension(290, 230));

        jLbTitle_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_creditPanel.setText("Star Info");

        jLbName_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbName_creditPanel.setText("Name");

        jTFName_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTFGender_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbGender_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbGender_creditPanel.setText("Gender");

        jLbType_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbType_creditPanel.setText("Type");

        jTFType_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbCharacter_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbCharacter_creditPanel.setText("Character");

        jTFCharacter_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbPosition_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbPosition_creditPanel.setText("Position");

        jTFPosition_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jBtnSave_creditPanel.setText("Save");
        jBtnSave_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_creditPanelActionPerformed(evt);
            }
        });

        jBtnRemove_creditPanel.setText("Remove");
        jBtnRemove_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_creditPanelActionPerformed(evt);
            }
        });

        jBtnNew_creditPanel.setText("New");
        jBtnNew_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_creditPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCreditInfoLayout = new javax.swing.GroupLayout(jPanelCreditInfo);
        jPanelCreditInfo.setLayout(jPanelCreditInfoLayout);
        jPanelCreditInfoLayout.setHorizontalGroup(
            jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLbTitle_creditPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbName_creditPanel)
                    .addComponent(jLbType_creditPanel)
                    .addComponent(jLbGender_creditPanel)
                    .addComponent(jLbCharacter_creditPanel)
                    .addComponent(jLbPosition_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFPosition_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCharacter_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFType_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFGender_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFName_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreditInfoLayout.createSequentialGroup()
                        .addComponent(jBtnNew_creditPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSave_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jBtnRemove_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelCreditInfoLayout.setVerticalGroup(
            jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLbTitle_creditPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbName_creditPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFName_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbGender_creditPanel)
                    .addComponent(jTFGender_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFType_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbType_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCharacter_creditPanel)
                    .addComponent(jTFCharacter_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPosition_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbPosition_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSave_creditPanel)
                    .addComponent(jBtnNew_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRemove_creditPanel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelCreditInfo, "CreditCard");

        jBtnNextCrad.setText(">>");
        jBtnNextCrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNextCradActionPerformed(evt);
            }
        });

        jBtnPrevCard.setText("<<");
        jBtnPrevCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrevCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPrevCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnNextCrad)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNextCrad)
                            .addComponent(jBtnPrevCard)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    private void jBtnInsertFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertFromFileActionPerformed
        
        CardLayout layout = (CardLayout) jPanel2.getLayout();
            
        JPopupMenu updateOption = new JPopupMenu("Update Option");
        JMenuItem credits = new JMenuItem("Stars");
        updateOption.add(credits);
        credits.addActionListener((ActionEvent e) -> {
            List<Credit> c = readFileCredits();
            c.forEach(i -> {
                creditsTableModel.addRow(new Object[] {i.getName(), i.getGender(), i.getType(), i.getCharacter(), i.getPosition()});
            });
            jTableCredits.validate();
        });
        JMenuItem locations = new JMenuItem("Locations");
        updateOption.add(locations);
        locations.addActionListener((ActionEvent e) -> {
            List<String> locs = readFileLocations();
            locs.forEach(i -> {
                locationsListModel.addElement(i);
            });
            jListLocations.validate();
        }); 
        JMenuItem relDates = new JMenuItem("Release Dates");
        updateOption.add(relDates);
        relDates.addActionListener((ActionEvent e) -> {
            List<ReleaseDate> rd = readFileReleaseDates();
            rd.forEach(i -> {
                releaseDatesTableModel.addRow(new Object[] {i.getCountry(), i.getDate()});
            });
            jTableReleaseDates.validate();
        }); 
        
        updateOption.show(jPanel1, jBtnInsertFromFile.getLocation().x, jBtnInsertFromFile.getLocation().y);
        
        
    }//GEN-LAST:event_jBtnInsertFromFileActionPerformed

    private void jBtnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinishActionPerformed
        String title = jTFTitle.getText();
        if(title.isBlank()) {
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        List<String> genres = new ArrayList<>();
        String[] genresTmp = jTAreaGenres.getText().split(",");
        for(String s: genresTmp) genres.add(s.trim());
        
        String runningTimes = jTFRunningtime.getText();
        if(runningTimes.isBlank()) {
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        
        List<String> keywords = new ArrayList<>();
        String[] keywordsTmp = jTextKeywords.getText().split(",");
        if(jTextKeywords.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        for(String s: keywordsTmp) keywords.add(s.trim());        
        
        List<String> languages = new ArrayList<>();
        if(languagesListModel.isEmpty()){
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        for(int i=0;i<languagesListModel.getSize(); i++) {
            languages.add(languagesListModel.get(i).toString());
        }
        
        List<String> locations = new ArrayList<>();
        if(locationsListModel.isEmpty()){
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        for(int i=0;i<locationsListModel.getSize(); i++) {
            locations.add(locationsListModel.get(i).toString());
        }
        
        List<ReleaseDate> relDates = new ArrayList<>();
        if(releaseDatesTableModel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        int year = Integer.MAX_VALUE;
        for(int i=0; i<releaseDatesTableModel.getRowCount();i++) {
            String date = releaseDatesTableModel.getValueAt(i, 0).toString();
            String country = releaseDatesTableModel.getValueAt(i, 1).toString();
            Pattern pattern = Pattern.compile("(\\d{4})");
            Matcher matcher = pattern.matcher(date);
            matcher.find();
            int minYear = Integer.parseInt(matcher.group(1));
            if(minYear<year) year=minYear;
            relDates.add(new ReleaseDate(country, date));
        }
        
        List<Credit> credits = new ArrayList<>();
        if(creditsTableModel.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Invalid data", "Error", ERROR_MESSAGE);
            return;
        }
        for(int i=0; i<creditsTableModel.getRowCount();i++) {
            credits.add(new Credit(
                creditsTableModel.getValueAt(i, 0).toString(), 
                creditsTableModel.getValueAt(i, 1).toString(),
                creditsTableModel.getValueAt(i, 2).toString(),
                creditsTableModel.getValueAt(i, 3).toString(),
                Integer.parseInt(creditsTableModel.getValueAt(i, 4).toString())
            ));
        }
        
        Movie movie = new Movie(title, year, genres, keywords, languages, locations, relDates, runningTimes, credits);
        movieDao.createMovie(movie);
        JOptionPane.showMessageDialog(this, "Insert successfully");
        this.dispose();
    }//GEN-LAST:event_jBtnFinishActionPerformed

    private void jTableCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCreditsMouseClicked
                       
        int row = jTableCredits.getSelectedRow();
        jTFName_creditPanel.setText((String) creditsTableModel.getValueAt(row, 0));
        jTFGender_creditPanel.setText((String) creditsTableModel.getValueAt(row, 1));
        jTFType_creditPanel.setText((String) creditsTableModel.getValueAt(row, 2));
        jTFCharacter_creditPanel.setText((String) creditsTableModel.getValueAt(row, 3));
        jTFPosition_creditPanel.setText(creditsTableModel.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTableCreditsMouseClicked

    private void jBtnNew_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_creditPanelActionPerformed
        jTableCredits.clearSelection();
        jTFName_creditPanel.setText("");
        jTFGender_creditPanel.setText("");
        jTFType_creditPanel.setText("");
        jTFCharacter_creditPanel.setText("");
        jTFPosition_creditPanel.setText("");
        
    }//GEN-LAST:event_jBtnNew_creditPanelActionPerformed

    private void jBtnSave_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_creditPanelActionPerformed
        String name = jTFName_creditPanel.getText();
        String gender =  jTFGender_creditPanel.getText();
        String type = jTFType_creditPanel.getText();
        String character = jTFCharacter_creditPanel.getText();
        int pos = Integer.parseInt(jTFPosition_creditPanel.getText());
        creditsTableModel.addRow(new Object[]{name, gender, type, character, pos});        
        jTableCredits.validate();
       
    }//GEN-LAST:event_jBtnSave_creditPanelActionPerformed

    private void jBtnRemove_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_creditPanelActionPerformed
        int row = jTableCredits.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
            return;
        }        
        creditsTableModel.removeRow(row);
        jTableCredits.validate();        
    }//GEN-LAST:event_jBtnRemove_creditPanelActionPerformed

    private void jListLocationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLocationsMouseClicked
        String selectedItem = jListLocations.getSelectedValue();
        jTFLocation_locationPanel.setText(selectedItem);
    }//GEN-LAST:event_jListLocationsMouseClicked

    private void jBtnNew_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_locationPanelActionPerformed
        jListLocations.clearSelection();
        jTFLocation_locationPanel.setText("");
    }//GEN-LAST:event_jBtnNew_locationPanelActionPerformed

    private void jBtnSave_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_locationPanelActionPerformed
        String value = jTFLocation_locationPanel.getText();
        locationsListModel.addElement(value);
        
    }//GEN-LAST:event_jBtnSave_locationPanelActionPerformed

    private void jBtnRemove_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_locationPanelActionPerformed
        int selectedRow = jListLocations.getSelectedIndex();
        if(selectedRow==-1) JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
        locationsListModel.remove(selectedRow);
    }//GEN-LAST:event_jBtnRemove_locationPanelActionPerformed

    private void jListLanguagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLanguagesMouseClicked
        String selectedItem = jListLanguages.getSelectedValue();
        jTFLanguage_languagePanel.setText(selectedItem);
    }//GEN-LAST:event_jListLanguagesMouseClicked

    private void jBtnNew_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_languagePanelActionPerformed
        jListLanguages.clearSelection();
        jTFLanguage_languagePanel.setText("");
    }//GEN-LAST:event_jBtnNew_languagePanelActionPerformed

    private void jBtnSave_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_languagePanelActionPerformed
        String value = jTFLanguage_languagePanel.getText();
        languagesListModel.addElement(value);
        
    }//GEN-LAST:event_jBtnSave_languagePanelActionPerformed

    private void jBtnRemove_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_languagePanelActionPerformed
        int selectedRow = jListLanguages.getSelectedIndex();
        if(selectedRow==-1) JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
        languagesListModel.remove(selectedRow);
    }//GEN-LAST:event_jBtnRemove_languagePanelActionPerformed

    private void jTableReleaseDatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReleaseDatesMouseClicked
        int row = jTableReleaseDates.getSelectedRow();
        jTFDate_relDatePanel.setText((String) releaseDatesTableModel.getValueAt(row, 0));
        jTFCountry_relDatePanel.setText((String) releaseDatesTableModel.getValueAt(row, 1));
    }//GEN-LAST:event_jTableReleaseDatesMouseClicked

    private void jBtnNew_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_relDatePanelActionPerformed
        jTableReleaseDates.clearSelection();
        jTFDate_relDatePanel.setText("");
        jTFCountry_relDatePanel.setText("");
    }//GEN-LAST:event_jBtnNew_relDatePanelActionPerformed

    private void jBtnSave_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_relDatePanelActionPerformed
        String date = jTFDate_relDatePanel.getText();
        String country = jTFCountry_relDatePanel.getText();
        releaseDatesTableModel.addRow(new Object[] {date, country});
    }//GEN-LAST:event_jBtnSave_relDatePanelActionPerformed

    private void jBtnRemove_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_relDatePanelActionPerformed
        releaseDatesTableModel.removeRow(jTableReleaseDates.getSelectedRow());
    }//GEN-LAST:event_jBtnRemove_relDatePanelActionPerformed

    private void jBtnPrevCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrevCardActionPerformed
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.previous(jPanel2);
    }//GEN-LAST:event_jBtnPrevCardActionPerformed

    private void jBtnNextCradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextCradActionPerformed
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_jBtnNextCradActionPerformed

    private List<Credit> readFileCredits() {
        List<Credit> objList = new ArrayList<>();
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = fileChooser.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            
            try {
                File myObj = fileChooser.getSelectedFile();
                Scanner myReader = new Scanner(myObj);                
                while (myReader.hasNextLine()) {
                    String[] data = myReader.nextLine().split("|");
                    Credit c = new Credit(data[0].trim(), data[1].trim(), data[2].trim(), data[3].trim(), Integer.parseInt(data[4].trim()));
                    objList.add(c);
                }
                myReader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InsertFrame.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        return objList;
    }
    
    private List<String> readFileLocations() {
        List<String> objList = new ArrayList<>();
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = fileChooser.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            
            try {
                File myObj = fileChooser.getSelectedFile();
                Scanner myReader = new Scanner(myObj);                
                while (myReader.hasNextLine()) {
                    String data = myReader.nextLine().trim();
                    objList.add(data);
                }
                myReader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InsertFrame.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        return objList;
    }
    
    private List<ReleaseDate> readFileReleaseDates() {
        List<ReleaseDate> objList = new ArrayList<>();
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = fileChooser.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            
            try {
                File myObj = fileChooser.getSelectedFile();
                Scanner myReader = new Scanner(myObj);                
                while (myReader.hasNextLine()) {
                    String[] data = myReader.nextLine().split("|");
                    ReleaseDate relDate = new ReleaseDate(data[0].trim(), data[1].trim());                    
                    objList.add(relDate);
                }
                myReader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InsertFrame.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        return objList;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InsertFrame m = new InsertFrame();
                m.setVisible(true);
            }
        });
    }

    MovieDAO movieDao;
    DefaultListModel locationsListModel;
    DefaultListModel languagesListModel;
    DefaultTableModel creditsTableModel;
    DefaultTableModel releaseDatesTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFinish;
    private javax.swing.JButton jBtnInsertFromFile;
    private javax.swing.JButton jBtnNew_creditPanel;
    private javax.swing.JButton jBtnNew_languagePanel;
    private javax.swing.JButton jBtnNew_locationPanel;
    private javax.swing.JButton jBtnNew_relDatePanel;
    private javax.swing.JButton jBtnNextCrad;
    private javax.swing.JButton jBtnPrevCard;
    private javax.swing.JButton jBtnRemove_creditPanel;
    private javax.swing.JButton jBtnRemove_languagePanel;
    private javax.swing.JButton jBtnRemove_locationPanel;
    private javax.swing.JButton jBtnRemove_relDatePanel;
    private javax.swing.JButton jBtnSave_creditPanel;
    private javax.swing.JButton jBtnSave_languagePanel;
    private javax.swing.JButton jBtnSave_locationPanel;
    private javax.swing.JButton jBtnSave_relDatePanel;
    private javax.swing.JLabel jLbCharacter_creditPanel;
    private javax.swing.JLabel jLbCountry_relDatePanel;
    private javax.swing.JLabel jLbCredits;
    private javax.swing.JLabel jLbDate_relDatePanel;
    private javax.swing.JLabel jLbGender_creditPanel;
    private javax.swing.JLabel jLbGenres;
    private javax.swing.JLabel jLbKeywords;
    private javax.swing.JLabel jLbLanguages;
    private javax.swing.JLabel jLbLocations;
    private javax.swing.JLabel jLbName_creditPanel;
    private javax.swing.JLabel jLbPosition_creditPanel;
    private javax.swing.JLabel jLbReleaseDate;
    private javax.swing.JLabel jLbRunningTimes;
    private javax.swing.JLabel jLbTitle;
    private javax.swing.JLabel jLbTitle_creditPanel;
    private javax.swing.JLabel jLbTitle_languagePanel;
    private javax.swing.JLabel jLbTitle_locationPanel;
    private javax.swing.JLabel jLbTitle_relDatePanel;
    private javax.swing.JLabel jLbType_creditPanel;
    private javax.swing.JList<String> jListLanguages;
    private javax.swing.JList<String> jListLocations;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCreditInfo;
    private javax.swing.JPanel jPanelLanguageInfo;
    private javax.swing.JPanel jPanelLocationInfo;
    private javax.swing.JPanel jPanelReleaseDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTAreaGenres;
    private javax.swing.JTextField jTFCharacter_creditPanel;
    private javax.swing.JTextField jTFCountry_relDatePanel;
    private javax.swing.JTextField jTFDate_relDatePanel;
    private javax.swing.JTextField jTFGender_creditPanel;
    private javax.swing.JTextField jTFLanguage_languagePanel;
    private javax.swing.JTextField jTFLocation_locationPanel;
    private javax.swing.JTextField jTFName_creditPanel;
    private javax.swing.JTextField jTFPosition_creditPanel;
    private javax.swing.JTextField jTFRunningtime;
    private javax.swing.JTextField jTFTitle;
    private javax.swing.JTextField jTFType_creditPanel;
    private javax.swing.JTable jTableCredits;
    private javax.swing.JTable jTableReleaseDates;
    private javax.swing.JTextArea jTextKeywords;
    // End of variables declaration//GEN-END:variables
}
