/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.moviemanagement.GUI;

import com.mycompany.moviemanagement.Models.Credit;
import com.mycompany.moviemanagement.Models.Movie;
import com.mycompany.moviemanagement.Models.ReleaseDate;
import com.mycompany.moviemanagement.Models.UserResponse;
import com.mycompany.moviemanagement.Repositories.MovieDAO;
import com.mycompany.moviemanagement.Repositories.MovieDAOImp;
import com.mycompany.moviemanagement.Repositories.UserDAO;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPopupMenu;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nhath
 */
public class MovieInfoFrame extends java.awt.Frame {
    
    /**
     * Creates new form MovieInfoFrame
     * @param movie
     * @param userDao
     */
    public MovieInfoFrame(Movie movie, UserDAO userDao) {
        this.userDao = userDao;
        this.movieDao = new MovieDAOImp();
        this.movie=movie;
        creditsTableModel = new DefaultTableModel(new String[] {"ID", "Name", "Gender", "Type", "Chacracter", "Position"}, 0);
        this.movie.getCredits().forEach(c -> {
            creditsTableModel.addRow(new Object[]{c.getId(), c.getName(), c.getGender(), c.getType(), c.getCharacter(), c.getPosition()});
        });
        releaseDatesTableModel = new DefaultTableModel(new String[] {"Release date", "Country"}, 0);
        this.movie.getReleaseDates().forEach(r -> {
            releaseDatesTableModel.addRow(new Object[] {r.getDate(), r.getCountry()});
        });
        languagesListModel = new DefaultListModel();
        this.movie.getLanguages().forEach(l -> {
            languagesListModel.addElement(l);
        });
        locationsListModel = new DefaultListModel();
        this.movie.getLocations().forEach(l -> {
            locationsListModel.addElement(l);
        });
        
        initComponents();
        // Fill up data on frame
        jTFTitle.setText(movie.getTitle());
        jTFRunningtime.setText(movie.getRunningtimes());
        jTAreaGenres.setText(String.join(", ", movie.getGenres()));
        jTextKeywords.setText(String.join(", ", movie.getKeywords()));       
        //jTableCredits.removeColumn(jTableCredits.getColumn("ID"));
        jTableCredits.setSelectionMode(SINGLE_SELECTION);
        jPanel2.setVisible(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbTitle = new javax.swing.JLabel();
        jLbGenres = new javax.swing.JLabel();
        jLbReleaseDate = new javax.swing.JLabel();
        jLbLanguages = new javax.swing.JLabel();
        jLbCredits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCredits = new javax.swing.JTable();
        jLbLocations = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLocations = new javax.swing.JList<>();
        jLbRunningTimes = new javax.swing.JLabel();
        jLbKeywords = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextKeywords = new javax.swing.JTextArea();
        jBtnMarkWatched = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnAddfavorites = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jTFTitle = new javax.swing.JTextField();
        jTFRunningtime = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAreaGenres = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListLanguages = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableReleaseDates = new javax.swing.JTable();
        jBtnExport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelLocationInfo = new javax.swing.JPanel();
        jLbTitle_locationPanel = new javax.swing.JLabel();
        jTFLocation_locationPanel = new javax.swing.JTextField();
        jBtnRemove_locationPanel = new javax.swing.JButton();
        jBtnNew_locationPanel = new javax.swing.JButton();
        jBtnSave_locationPanel = new javax.swing.JButton();
        jBtnFinish_locationPanel = new javax.swing.JButton();
        jPanelLanguageInfo = new javax.swing.JPanel();
        jLbTitle_languagePanel = new javax.swing.JLabel();
        jTFLanguage_languagePanel = new javax.swing.JTextField();
        jBtnRemove_languagePanel = new javax.swing.JButton();
        jBtnNew_languagePanel = new javax.swing.JButton();
        jBtnSave_languagePanel = new javax.swing.JButton();
        jBtnFinish_languagePanel = new javax.swing.JButton();
        jPanelReleaseDate = new javax.swing.JPanel();
        jLbTitle_relDatePanel = new javax.swing.JLabel();
        jLbDate_relDatePanel = new javax.swing.JLabel();
        jTFDate_relDatePanel = new javax.swing.JTextField();
        jTFCountry_relDatePanel = new javax.swing.JTextField();
        jLbCountry_relDatePanel = new javax.swing.JLabel();
        jBtnRemove_relDatePanel = new javax.swing.JButton();
        jBtnNew_relDatePanel = new javax.swing.JButton();
        jBtnSave_relDatePanel = new javax.swing.JButton();
        jBtnDone_relDatePanel = new javax.swing.JButton();
        jPanelCreditInfo = new javax.swing.JPanel();
        jLbTitle_creditPanel = new javax.swing.JLabel();
        jLbName_creditPanel = new javax.swing.JLabel();
        jTFName_creditPanel = new javax.swing.JTextField();
        jTFGender_creditPanel = new javax.swing.JTextField();
        jLbGender_creditPanel = new javax.swing.JLabel();
        jLbType_creditPanel = new javax.swing.JLabel();
        jTFType_creditPanel = new javax.swing.JTextField();
        jLbCharacter_creditPanel = new javax.swing.JLabel();
        jTFCharacter_creditPanel = new javax.swing.JTextField();
        jLbPosition_creditPanel = new javax.swing.JLabel();
        jTFPosition_creditPanel = new javax.swing.JTextField();
        jBtnEdit_creditPanel = new javax.swing.JButton();
        jBtnSave_creditPanel = new javax.swing.JButton();
        jBtnRemove_creditPanel = new javax.swing.JButton();
        jBtnNew_creditPanel = new javax.swing.JButton();
        jBtnFinish_creditPanel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setToolTipText("Info");
        jPanel1.setPreferredSize(new java.awt.Dimension(764, 1000));

        jLbTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbTitle.setText("Title:");

        jLbGenres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbGenres.setText("Genres:");

        jLbReleaseDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbReleaseDate.setText("Running times:");

        jLbLanguages.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbLanguages.setText("Languages:");

        jLbCredits.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbCredits.setText("Stars:");

        jTableCredits.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTableCredits.setModel(creditsTableModel);
        jTableCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCreditsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCredits);

        jLbLocations.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbLocations.setText("Locations:");

        jListLocations.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jListLocations.setModel(locationsListModel);
        jListLocations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLocationsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListLocations);

        jLbRunningTimes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbRunningTimes.setText("Release dates");

        jLbKeywords.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbKeywords.setText("Keywords:");

        jTextKeywords.setEditable(false);
        jTextKeywords.setColumns(20);
        jTextKeywords.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextKeywords.setRows(5);
        jTextKeywords.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextKeywordsFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTextKeywords);

        jBtnMarkWatched.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnMarkWatched.setText("Mark as watched");
        jBtnMarkWatched.setEnabled(!userDao.isMovieInUserWatchedMovies(movie.getId()));
        jBtnMarkWatched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMarkWatchedActionPerformed(evt);
            }
        });

        jBtnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnBack.setText("Back");
        jBtnBack.setToolTipText("");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jBtnAddfavorites.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnAddfavorites.setText("Add favorites");
        jBtnAddfavorites.setEnabled(!userDao.isMovieInUserWishlist(movie.getId()));
        jBtnAddfavorites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddfavoritesActionPerformed(evt);
            }
        });

        jBtnUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnUpdate.setText("Update");
        jBtnUpdate.setVisible(this.userDao.isAdmin());

        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jTFTitle.setEditable(false);
        jTFTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTitleFocusLost(evt);
            }
        });

        jTFRunningtime.setEditable(false);
        jTFRunningtime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFRunningtimeFocusLost(evt);
            }
        });

        jTAreaGenres.setEditable(false);
        jTAreaGenres.setColumns(20);
        jTAreaGenres.setRows(5);
        jTAreaGenres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTAreaGenresFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(jTAreaGenres);

        jListLanguages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListLanguages.setModel(languagesListModel);
        jListLanguages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLanguagesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListLanguages);

        jTableReleaseDates.setModel(releaseDatesTableModel);
        jTableReleaseDates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReleaseDatesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableReleaseDates);

        jBtnExport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnExport.setText("Export data");
        jBtnExport.setEnabled(userDao.isAdmin());
        jBtnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbTitle)
                    .addComponent(jLbReleaseDate)
                    .addComponent(jLbGenres)
                    .addComponent(jLbCredits)
                    .addComponent(jLbLocations)
                    .addComponent(jLbLanguages)
                    .addComponent(jLbRunningTimes)
                    .addComponent(jLbKeywords))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4)
                            .addComponent(jTFRunningtime)
                            .addComponent(jTFTitle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnExport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnAddfavorites, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnMarkWatched, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(74, 74, 74))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3, jScrollPane4, jScrollPane5, jScrollPane6, jTFRunningtime, jTFTitle});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbTitle)
                    .addComponent(jTFTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbReleaseDate)
                    .addComponent(jTFRunningtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbGenres)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbCredits))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbLanguages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbRunningTimes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbKeywords))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnUpdate)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAddfavorites)
                        .addComponent(jBtnMarkWatched)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBack)
                    .addComponent(jBtnExport))
                .addGap(400, 400, 400))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 220));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLbTitle_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_locationPanel.setText("Location Info");

        jTFLocation_locationPanel.setEditable(false);

        jBtnRemove_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_locationPanel.setText("Remove");
        jBtnRemove_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_locationPanelActionPerformed(evt);
            }
        });

        jBtnNew_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_locationPanel.setText("New");
        jBtnNew_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_locationPanelActionPerformed(evt);
            }
        });

        jBtnSave_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_locationPanel.setText("Save");
        jBtnSave_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_locationPanelActionPerformed(evt);
            }
        });

        jBtnFinish_locationPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnFinish_locationPanel.setText("Done");
        jBtnFinish_locationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinish_locationPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLocationInfoLayout = new javax.swing.GroupLayout(jPanelLocationInfo);
        jPanelLocationInfo.setLayout(jPanelLocationInfoLayout);
        jPanelLocationInfoLayout.setHorizontalGroup(
            jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocationInfoLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addComponent(jLbTitle_locationPanel)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnRemove_locationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnFinish_locationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addComponent(jBtnNew_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnSave_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLocationInfoLayout.createSequentialGroup()
                        .addComponent(jTFLocation_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanelLocationInfoLayout.setVerticalGroup(
            jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocationInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitle_locationPanel)
                .addGap(18, 18, 18)
                .addComponent(jTFLocation_locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLocationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSave_locationPanel)
                    .addComponent(jBtnNew_locationPanel))
                .addGap(18, 18, 18)
                .addComponent(jBtnRemove_locationPanel)
                .addGap(26, 26, 26)
                .addComponent(jBtnFinish_locationPanel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelLocationInfo, "LocationCard");

        jLbTitle_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_languagePanel.setText("Language Info");

        jTFLanguage_languagePanel.setEditable(false);
        jTFLanguage_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jBtnRemove_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_languagePanel.setText("Remove");
        jBtnRemove_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_languagePanelActionPerformed(evt);
            }
        });

        jBtnNew_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_languagePanel.setText("New");
        jBtnNew_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_languagePanelActionPerformed(evt);
            }
        });

        jBtnSave_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_languagePanel.setText("Save");
        jBtnSave_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_languagePanelActionPerformed(evt);
            }
        });

        jBtnFinish_languagePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnFinish_languagePanel.setText("Done");
        jBtnFinish_languagePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinish_languagePanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLanguageInfoLayout = new javax.swing.GroupLayout(jPanelLanguageInfo);
        jPanelLanguageInfo.setLayout(jPanelLanguageInfoLayout);
        jPanelLanguageInfoLayout.setHorizontalGroup(
            jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLanguageInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbTitle_languagePanel)
                .addGap(124, 124, 124))
            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                                .addComponent(jBtnNew_languagePanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSave_languagePanel))
                            .addComponent(jTFLanguage_languagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnRemove_languagePanel)
                            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jBtnFinish_languagePanel)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanelLanguageInfoLayout.setVerticalGroup(
            jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLanguageInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLbTitle_languagePanel)
                .addGap(18, 18, 18)
                .addComponent(jTFLanguage_languagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLanguageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNew_languagePanel)
                    .addComponent(jBtnSave_languagePanel))
                .addGap(18, 18, 18)
                .addComponent(jBtnRemove_languagePanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnFinish_languagePanel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelLanguageInfo, "languageCard");

        jLbTitle_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_relDatePanel.setText("Release Date Info");

        jLbDate_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbDate_relDatePanel.setText("Date");

        jTFDate_relDatePanel.setEditable(false);
        jTFDate_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTFCountry_relDatePanel.setEditable(false);
        jTFCountry_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbCountry_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbCountry_relDatePanel.setText("Country");

        jBtnRemove_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnRemove_relDatePanel.setText("Remove");
        jBtnRemove_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_relDatePanelActionPerformed(evt);
            }
        });

        jBtnNew_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnNew_relDatePanel.setText("New");
        jBtnNew_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_relDatePanelActionPerformed(evt);
            }
        });

        jBtnSave_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnSave_relDatePanel.setText("Save");
        jBtnSave_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_relDatePanelActionPerformed(evt);
            }
        });

        jBtnDone_relDatePanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBtnDone_relDatePanel.setText("Done");
        jBtnDone_relDatePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDone_relDatePanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReleaseDateLayout = new javax.swing.GroupLayout(jPanelReleaseDate);
        jPanelReleaseDate.setLayout(jPanelReleaseDateLayout);
        jPanelReleaseDateLayout.setHorizontalGroup(
            jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFDate_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                                .addComponent(jLbTitle_relDatePanel)
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBtnRemove_relDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnDone_relDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReleaseDateLayout.createSequentialGroup()
                        .addComponent(jBtnSave_relDatePanel)
                        .addGap(33, 33, 33))))
            .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jBtnNew_relDatePanel))
                    .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbDate_relDatePanel)
                            .addComponent(jLbCountry_relDatePanel))
                        .addGap(37, 37, 37)
                        .addComponent(jTFCountry_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelReleaseDateLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTFCountry_relDatePanel, jTFDate_relDatePanel});

        jPanelReleaseDateLayout.setVerticalGroup(
            jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReleaseDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitle_relDatePanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbDate_relDatePanel)
                    .addComponent(jTFDate_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCountry_relDatePanel)
                    .addComponent(jTFCountry_relDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelReleaseDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNew_relDatePanel)
                    .addComponent(jBtnSave_relDatePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnRemove_relDatePanel)
                .addGap(18, 18, 18)
                .addComponent(jBtnDone_relDatePanel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelReleaseDate, "RelDateCard");

        jPanelCreditInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanelCreditInfo.setPreferredSize(new java.awt.Dimension(290, 230));

        jLbTitle_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbTitle_creditPanel.setText("Star Info");

        jLbName_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbName_creditPanel.setText("Name");

        jTFName_creditPanel.setEditable(false);
        jTFName_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTFGender_creditPanel.setEditable(false);
        jTFGender_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbGender_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbGender_creditPanel.setText("Gender");

        jLbType_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbType_creditPanel.setText("Type");

        jTFType_creditPanel.setEditable(false);
        jTFType_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbCharacter_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbCharacter_creditPanel.setText("Character");

        jTFCharacter_creditPanel.setEditable(false);
        jTFCharacter_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLbPosition_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLbPosition_creditPanel.setText("Position");

        jTFPosition_creditPanel.setEditable(false);
        jTFPosition_creditPanel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jBtnEdit_creditPanel.setText("Edit");
        jBtnEdit_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEdit_creditPanelActionPerformed(evt);
            }
        });

        jBtnSave_creditPanel.setText("Save");
        jBtnSave_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSave_creditPanelActionPerformed(evt);
            }
        });

        jBtnRemove_creditPanel.setText("Remove");
        jBtnRemove_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemove_creditPanelActionPerformed(evt);
            }
        });

        jBtnNew_creditPanel.setText("New");
        jBtnNew_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNew_creditPanelActionPerformed(evt);
            }
        });

        jBtnFinish_creditPanel.setText("Done");
        jBtnFinish_creditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinish_creditPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCreditInfoLayout = new javax.swing.GroupLayout(jPanelCreditInfo);
        jPanelCreditInfo.setLayout(jPanelCreditInfoLayout);
        jPanelCreditInfoLayout.setHorizontalGroup(
            jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLbTitle_creditPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                        .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbName_creditPanel)
                            .addComponent(jLbType_creditPanel)
                            .addComponent(jLbGender_creditPanel)
                            .addComponent(jLbCharacter_creditPanel)
                            .addComponent(jLbPosition_creditPanel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFPosition_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCharacter_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFType_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFGender_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFName_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                                .addComponent(jBtnEdit_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSave_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jBtnNew_creditPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnRemove_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnFinish_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelCreditInfoLayout.setVerticalGroup(
            jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreditInfoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLbTitle_creditPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbName_creditPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFName_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbGender_creditPanel)
                    .addComponent(jTFGender_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFType_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbType_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCharacter_creditPanel)
                    .addComponent(jTFCharacter_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPosition_creditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbPosition_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEdit_creditPanel)
                    .addComponent(jBtnSave_creditPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRemove_creditPanel)
                    .addComponent(jBtnFinish_creditPanel)
                    .addComponent(jBtnNew_creditPanel))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelCreditInfo, "CreditCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        dispose();
    }//GEN-LAST:event_exitForm

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        
        CardLayout layout = (CardLayout) jPanel2.getLayout();
            
        JPopupMenu updateOption = new JPopupMenu("Update Option");
        JMenuItem title = new JMenuItem("Title");
        updateOption.add(title);
        title.addActionListener((ActionEvent e) -> {
            jTFTitle.setEditable(true);
            jTFTitle.requestFocus();
        });  
        JMenuItem genres = new JMenuItem("Genres");
        updateOption.add(genres);
        genres.addActionListener((ActionEvent e) -> {
            jTAreaGenres.setEditable(true);
            jTAreaGenres.requestFocus();
        }); 
        JMenuItem runningtimes = new JMenuItem("Running Times");
        updateOption.add(runningtimes);
        runningtimes.addActionListener((ActionEvent e) -> {
            jTFRunningtime.setEditable(true);
            jTFRunningtime.requestFocus();
        }); 
        JMenuItem credits = new JMenuItem("Stars");
        updateOption.add(credits);
        credits.addActionListener((ActionEvent e) -> {
            jPanel2.setVisible(true);
            layout.show(jPanel2, "CreditCard");
        }); 
        JMenuItem keywords = new JMenuItem("Keywords");
        updateOption.add(keywords);
        keywords.addActionListener((ActionEvent e) -> {
            jTextKeywords.setEditable(true);
            jTextKeywords.requestFocus();
        }); 
        JMenuItem languages = new JMenuItem("Languages");
        updateOption.add(languages);
        languages.addActionListener((ActionEvent e) -> {
            jPanel2.setVisible(true);
            layout.show(jPanel2, "languageCard");
        }); 
        JMenuItem locations = new JMenuItem("Locations");
        updateOption.add(locations);
        locations.addActionListener((ActionEvent e) -> {
            jPanel2.setVisible(true);
            layout.show(jPanel2, "LocationCard");
        }); 
        JMenuItem relDates = new JMenuItem("Release Dates");
        updateOption.add(relDates);
        relDates.addActionListener((ActionEvent e) -> {
            jPanel2.setVisible(true);
            layout.show(jPanel2, "RelDateCard");
        }); 
        
        updateOption.show(jPanel1, jBtnUpdate.getLocation().x, jBtnUpdate.getLocation().y);
        
        
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnAddfavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddfavoritesActionPerformed
        UserResponse res = userDao.addMovieToUserWishlist(movie.getId());
        if(res.success) JOptionPane.showMessageDialog(this, res.successMessage);
        else JOptionPane.showMessageDialog(this, res.errorMessage, "Error", ERROR_MESSAGE);
    }//GEN-LAST:event_jBtnAddfavoritesActionPerformed

    private void jBtnMarkWatchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMarkWatchedActionPerformed
        UserResponse res = userDao.addMovieToUserWatchedMovies(movie.getId());
        if(res.success) JOptionPane.showMessageDialog(this, res.successMessage);
        else JOptionPane.showMessageDialog(this, res.errorMessage, "Error", ERROR_MESSAGE);
    }//GEN-LAST:event_jBtnMarkWatchedActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jTFTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTitleFocusLost
        String newTitle = jTFTitle.getText();
        movie.setTitle(newTitle);
        movieDao.updateMovie(movie, UPDATE_OPTION[0]);
        jTFTitle.setEditable(false);
    }//GEN-LAST:event_jTFTitleFocusLost

    private void jTFRunningtimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFRunningtimeFocusLost
        String newRunningtime = jTFRunningtime.getText();
        movie.setRunningtimes(newRunningtime);
        movieDao.updateMovie(movie, UPDATE_OPTION[8]);
        jTFRunningtime.setEditable(false);
    }//GEN-LAST:event_jTFRunningtimeFocusLost

    private void jTAreaGenresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTAreaGenresFocusLost
        List<String> newGenres = new ArrayList<>();
        newGenres.addAll(Arrays.asList(jTAreaGenres.getText().split(", ")));
        movie.setGenres(newGenres);
        movieDao.updateMovie(movie, UPDATE_OPTION[1]);
        jTAreaGenres.setEditable(false);
    }//GEN-LAST:event_jTAreaGenresFocusLost

    private void jTextKeywordsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextKeywordsFocusLost
        List<String> newKeywords = new ArrayList<>();
        newKeywords.addAll(Arrays.asList(jTextKeywords.getText().split(", ")));
        movie.setGenres(newKeywords);
        movieDao.updateMovie(movie, UPDATE_OPTION[6]);
        jTextKeywords.setEditable(false);
    }//GEN-LAST:event_jTextKeywordsFocusLost

    private void jTableCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCreditsMouseClicked
                       
        int row = jTableCredits.getSelectedRow();
        jTFName_creditPanel.setText((String) creditsTableModel.getValueAt(row, 1));
        jTFGender_creditPanel.setText((String) creditsTableModel.getValueAt(row, 2));
        jTFType_creditPanel.setText((String) creditsTableModel.getValueAt(row, 3));
        jTFCharacter_creditPanel.setText((String) creditsTableModel.getValueAt(row, 4));
        jTFPosition_creditPanel.setText(creditsTableModel.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jTableCreditsMouseClicked

    private void jBtnEdit_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEdit_creditPanelActionPerformed
        jTFName_creditPanel.setEditable(true);
        jTFGender_creditPanel.setEditable(true);
        jTFType_creditPanel.setEditable(true);
        jTFCharacter_creditPanel.setEditable(true);
        jTFPosition_creditPanel.setEditable(true);
    }//GEN-LAST:event_jBtnEdit_creditPanelActionPerformed

    private void jBtnNew_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_creditPanelActionPerformed
        jTableCredits.clearSelection();
        if(!jTFName_creditPanel.isEditable()) jTFName_creditPanel.setEditable(true);
        if(!jTFGender_creditPanel.isEditable()) jTFGender_creditPanel.setEditable(true);
        if(!jTFType_creditPanel.isEditable()) jTFType_creditPanel.setEditable(true);
        if(!jTFCharacter_creditPanel.isEditable()) jTFCharacter_creditPanel.setEditable(true);
        if(!jTFPosition_creditPanel.isEditable()) jTFPosition_creditPanel.setEditable(true);
        jTFName_creditPanel.setText("");
        jTFGender_creditPanel.setText("");
        jTFType_creditPanel.setText("");
        jTFCharacter_creditPanel.setText("");
        jTFPosition_creditPanel.setText("");
        
    }//GEN-LAST:event_jBtnNew_creditPanelActionPerformed

    private void jBtnSave_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_creditPanelActionPerformed
        int row = jTableCredits.getSelectedRow();
        //System.out.println(row);
        String name = jTFName_creditPanel.getText();
        String gender =  jTFGender_creditPanel.getText();
        String type = jTFType_creditPanel.getText();
        String character = jTFCharacter_creditPanel.getText();
        int pos = Integer.parseInt(jTFPosition_creditPanel.getText());
        List<Credit> tmp = new ArrayList<>();
        Movie movieTmp;
        if(row != -1) {
            int id = Integer.parseInt(creditsTableModel.getValueAt(row, 0).toString());
            Credit updateCredit = new Credit(
                id, name, gender, type, character, pos
            );
            creditsTableModel.removeRow(row);
            creditsTableModel.addRow(new Object[] {id, name, gender, type, character, pos});
            tmp.add(updateCredit);
            movieTmp = new Movie(this.movie.getId(), tmp);            
            movieDao.updateMovie(movieTmp, UPDATE_OPTION[2]);
        }
        else {
            Credit insertCredit = new Credit(name, gender, type, character, pos);
            tmp.add(insertCredit);
            movieTmp = new Movie(this.movie.getId(), tmp);
            movieDao.updateMovie(movieTmp, UPDATE_OPTION[4]);
            int id = movieDao.getLatestInsertedPerson();
            creditsTableModel.addRow(new Object[]{id, name, gender, type, character, pos});
        }
        jTableCredits.validate();
       
    }//GEN-LAST:event_jBtnSave_creditPanelActionPerformed

    private void jBtnRemove_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_creditPanelActionPerformed
        int row = jTableCredits.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
            return;
        }
        
        List<Credit> tmp = new ArrayList<>();
        Credit updateCredit = new Credit(Integer.parseInt(creditsTableModel.getValueAt(row, 0).toString()));
        tmp.add(updateCredit);
        
        creditsTableModel.removeRow(row);
        jTableCredits.validate();
        
        Movie movieTmp = new Movie(movie.getId(), tmp);            
        movieDao.updateMovie(movieTmp, UPDATE_OPTION[3]);
        
    }//GEN-LAST:event_jBtnRemove_creditPanelActionPerformed

    private void jListLocationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLocationsMouseClicked
        String selectedItem = jListLocations.getSelectedValue();
        jTFLocation_locationPanel.setText(selectedItem);
    }//GEN-LAST:event_jListLocationsMouseClicked

    private void jBtnFinish_creditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinish_creditPanelActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jBtnFinish_creditPanelActionPerformed

    private void jBtnNew_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_locationPanelActionPerformed
        jListLocations.clearSelection();
        if(!jTFLocation_locationPanel.isEditable()) jTFLocation_locationPanel.setEditable(true);
        jTFLocation_locationPanel.setText("");
    }//GEN-LAST:event_jBtnNew_locationPanelActionPerformed

    private void jBtnSave_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_locationPanelActionPerformed
        String value = jTFLocation_locationPanel.getText();
        if(jListLocations.isSelectionEmpty()) {
            locationsListModel.addElement(value);
        }
        else {
            locationsListModel.remove(jListLocations.getSelectedIndex());
            locationsListModel.addElement(value);
        }
        List<String> locs = new ArrayList<>();
        for(Object obj: locationsListModel.toArray()){
            locs.add(obj.toString());
        }
        this.movie.setLocations(locs);
        movieDao.updateMovie(movie, UPDATE_OPTION[5]);
    }//GEN-LAST:event_jBtnSave_locationPanelActionPerformed

    private void jBtnRemove_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_locationPanelActionPerformed
        int selectedRow = jListLocations.getSelectedIndex();
        if(selectedRow==-1) JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
        locationsListModel.remove(selectedRow);
        List<String> locs = new ArrayList<>();
        for(Object obj: locationsListModel.toArray()){
            locs.add(obj.toString());
        }
        this.movie.setLocations(locs);
        movieDao.updateMovie(movie, UPDATE_OPTION[5]);
    }//GEN-LAST:event_jBtnRemove_locationPanelActionPerformed

    private void jBtnFinish_locationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinish_locationPanelActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jBtnFinish_locationPanelActionPerformed

    private void jListLanguagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLanguagesMouseClicked
        String selectedItem = jListLanguages.getSelectedValue();
        jTFLanguage_languagePanel.setText(selectedItem);
    }//GEN-LAST:event_jListLanguagesMouseClicked

    private void jBtnNew_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_languagePanelActionPerformed
        jListLanguages.clearSelection();
        if(!jTFLanguage_languagePanel.isEditable()) jTFLanguage_languagePanel.setEditable(true);
        jTFLanguage_languagePanel.setText("");
    }//GEN-LAST:event_jBtnNew_languagePanelActionPerformed

    private void jBtnSave_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_languagePanelActionPerformed
        String value = jTFLanguage_languagePanel.getText();
        if(jListLanguages.isSelectionEmpty()) {
            languagesListModel.addElement(value);
        }
        else {
            languagesListModel.remove(jListLanguages.getSelectedIndex());
            languagesListModel.addElement(value);
        }
        List<String> lans = new ArrayList<>();
        for(Object obj: languagesListModel.toArray()){
            lans.add(obj.toString());
        }
        this.movie.setLanguages(lans);
        movieDao.updateMovie(movie, UPDATE_OPTION[7]);
    }//GEN-LAST:event_jBtnSave_languagePanelActionPerformed

    private void jBtnRemove_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_languagePanelActionPerformed
        int selectedRow = jListLanguages.getSelectedIndex();
        if(selectedRow==-1) JOptionPane.showMessageDialog(this, "No row selected", "Warning", WARNING_MESSAGE);
        languagesListModel.remove(selectedRow);
        List<String> lans = new ArrayList<>();
        for(Object obj: languagesListModel.toArray()){
            lans.add(obj.toString());
        }
        this.movie.setLanguages(lans);
        movieDao.updateMovie(movie, UPDATE_OPTION[7]);
    }//GEN-LAST:event_jBtnRemove_languagePanelActionPerformed

    private void jBtnFinish_languagePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinish_languagePanelActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jBtnFinish_languagePanelActionPerformed

    private void jTableReleaseDatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReleaseDatesMouseClicked
        int row = jTableReleaseDates.getSelectedRow();
        jTFDate_relDatePanel.setText((String) releaseDatesTableModel.getValueAt(row, 0));
        jTFCountry_relDatePanel.setText((String) releaseDatesTableModel.getValueAt(row, 1));
    }//GEN-LAST:event_jTableReleaseDatesMouseClicked

    private void jBtnNew_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNew_relDatePanelActionPerformed
        jTableReleaseDates.clearSelection();
        if(!jTFDate_relDatePanel.isEditable()) jTFDate_relDatePanel.setEditable(true);
        if(!jTFCountry_relDatePanel.isEditable()) jTFCountry_relDatePanel.setEditable(true);
        jTFDate_relDatePanel.setText("");
        jTFCountry_relDatePanel.setText("");
    }//GEN-LAST:event_jBtnNew_relDatePanelActionPerformed

    private void jBtnSave_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSave_relDatePanelActionPerformed
        String date = jTFDate_relDatePanel.getText();
        String country = jTFCountry_relDatePanel.getText();
        releaseDatesTableModel.addRow(new Object[] {date, country});
        List<ReleaseDate> tmp = new ArrayList<>();
        for(int i=0; i<releaseDatesTableModel.getRowCount();i++) {
            tmp.add(new ReleaseDate(releaseDatesTableModel.getValueAt(i, 1).toString(), releaseDatesTableModel.getValueAt(i, 0).toString()));
        }
        this.movie.setReleaseDates(tmp);
        movieDao.updateMovie(movie, UPDATE_OPTION[9]);
    }//GEN-LAST:event_jBtnSave_relDatePanelActionPerformed

    private void jBtnRemove_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemove_relDatePanelActionPerformed
        int row = jTableReleaseDates.getSelectedRow();
        releaseDatesTableModel.removeRow(row);
        List<ReleaseDate> tmp = new ArrayList<>();
        for(int i=0; i<releaseDatesTableModel.getRowCount();i++) {
            tmp.add(new ReleaseDate(releaseDatesTableModel.getValueAt(i, 1).toString(), releaseDatesTableModel.getValueAt(i, 0).toString()));
        }
        this.movie.setReleaseDates(tmp);
        movieDao.updateMovie(movie, UPDATE_OPTION[9]);
    }//GEN-LAST:event_jBtnRemove_relDatePanelActionPerformed

    private void jBtnDone_relDatePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDone_relDatePanelActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jBtnDone_relDatePanelActionPerformed

    private void jBtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExportActionPerformed
        JFileChooser directory = new JFileChooser();
        directory.setFileSelectionMode(DIRECTORIES_ONLY);
        directory.setDialogTitle("Save movie data");
        int open = directory.showSaveDialog(null);
        String FILENAME = "/"+movie.getTitle().replaceAll(" ", "_") + ".xlsx";
        if(open==JFileChooser.APPROVE_OPTION){
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet(movie.getTitle());
            int row = 0;
            Row idRow = sheet.createRow(row++);
            idRow.createCell(0).setCellValue("ID: ");
            idRow.createCell(1).setCellValue(movie.getId());
            
            Row titleRow = sheet.createRow(row++);
            titleRow.createCell(0).setCellValue("Title: ");
            titleRow.createCell(1).setCellValue(movie.getTitle());
            
            Row yearRow = sheet.createRow(row++);
            yearRow.createCell(0).setCellValue("Year: ");
            yearRow.createCell(1).setCellValue(movie.getYear());
            
            Row genresRow = sheet.createRow(row++);
            genresRow.createCell(0).setCellValue("Genres: ");
            genresRow.createCell(1).setCellValue(String.join(", ", movie.getGenres()));
            
            Row runningtimeRow = sheet.createRow(row++);
            runningtimeRow.createCell(0).setCellValue("Running times: ");
            runningtimeRow.createCell(1).setCellValue( movie.getRunningtimes());
            
            Row starsRow = sheet.createRow(row++);
            starsRow.createCell(0).setCellValue("Stars: ");
            for(int i =0; i<movie.getCredits().size();i++){
                Row subrow = sheet.createRow(row++);
                Credit c = movie.getCredits().get(i);
                subrow.createCell(0).setCellValue(c.getId());
                subrow.createCell(1).setCellValue(c.getName());
                subrow.createCell(2).setCellValue(c.getGender());
                subrow.createCell(3).setCellValue(c.getType());
                subrow.createCell(4).setCellValue(c.getCharacter());
                subrow.createCell(5).setCellValue(c.getPosition());
            }
            
            Row relDatesRow = sheet.createRow(row++);
            relDatesRow.createCell(0).setCellValue("Release dates: ");
            for(int i =0; i<movie.getReleaseDates().size();i++){
                Row subrow = sheet.createRow(row++);
                ReleaseDate c = movie.getReleaseDates().get(i);
                subrow.createCell(0).setCellValue(c.getDate());
                subrow.createCell(1).setCellValue(c.getCountry());
            }
            
            Row languagesRow = sheet.createRow(row++);
            languagesRow.createCell(0).setCellValue("Languages: ");
            languagesRow.createCell(1).setCellValue(String.join(", ", movie.getLanguages()));
            
            Row locationsRow = sheet.createRow(row++);
            locationsRow.createCell(0).setCellValue("Locations: ");
            for(int i=0; i< movie.getLocations().size();i++){
                Row subrow = sheet.createRow(row++);
                subrow.createCell(0).setCellValue(movie.getLocations().get(i));
            }
            
            Row keywordsRow = sheet.createRow(row++);
            keywordsRow.createCell(0).setCellValue("Keywords: ");
            keywordsRow.createCell(1).setCellValue(String.join(", ", movie.getKeywords()));
            
            try (FileOutputStream outputStream = new FileOutputStream(directory.getSelectedFile() + FILENAME)) {
                workbook.write(outputStream);
                JOptionPane.showMessageDialog(this, "export successfully");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "An error occurred", "Error", ERROR_MESSAGE);
            } finally {
                try { workbook.close(); } 
                catch (IOException ex) { Logger.getLogger(MovieInfoFrame.class.getName()).log(Level.SEVERE, null, ex); }
            }
            
        }
        
    }//GEN-LAST:event_jBtnExportActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                MovieDAO dao = new MovieDAOImp();
//                Session s = new Session();
//                s.set(2);
//                UserDAO u = new UserDAOImp(s, true);
//                Movie mov = dao.getMovie(2544956);
//                MovieInfoFrame m = new MovieInfoFrame(mov, u);
//                m.setVisible(true);
//            }
//        });
//    }

    UserDAO userDao;
    Movie movie;
    MovieDAO movieDao;
    DefaultListModel locationsListModel;
    DefaultListModel languagesListModel;
    DefaultTableModel creditsTableModel;
    DefaultTableModel releaseDatesTableModel;
    final String[] UPDATE_OPTION = {"title", "genre", "updateCredit", "deleteCredit", "insertCredit","location", "keyword", "language", "runningtime", "releaseDate"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddfavorites;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnDone_relDatePanel;
    private javax.swing.JButton jBtnEdit_creditPanel;
    private javax.swing.JButton jBtnExport;
    private javax.swing.JButton jBtnFinish_creditPanel;
    private javax.swing.JButton jBtnFinish_languagePanel;
    private javax.swing.JButton jBtnFinish_locationPanel;
    private javax.swing.JButton jBtnMarkWatched;
    private javax.swing.JButton jBtnNew_creditPanel;
    private javax.swing.JButton jBtnNew_languagePanel;
    private javax.swing.JButton jBtnNew_locationPanel;
    private javax.swing.JButton jBtnNew_relDatePanel;
    private javax.swing.JButton jBtnRemove_creditPanel;
    private javax.swing.JButton jBtnRemove_languagePanel;
    private javax.swing.JButton jBtnRemove_locationPanel;
    private javax.swing.JButton jBtnRemove_relDatePanel;
    private javax.swing.JButton jBtnSave_creditPanel;
    private javax.swing.JButton jBtnSave_languagePanel;
    private javax.swing.JButton jBtnSave_locationPanel;
    private javax.swing.JButton jBtnSave_relDatePanel;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLbCharacter_creditPanel;
    private javax.swing.JLabel jLbCountry_relDatePanel;
    private javax.swing.JLabel jLbCredits;
    private javax.swing.JLabel jLbDate_relDatePanel;
    private javax.swing.JLabel jLbGender_creditPanel;
    private javax.swing.JLabel jLbGenres;
    private javax.swing.JLabel jLbKeywords;
    private javax.swing.JLabel jLbLanguages;
    private javax.swing.JLabel jLbLocations;
    private javax.swing.JLabel jLbName_creditPanel;
    private javax.swing.JLabel jLbPosition_creditPanel;
    private javax.swing.JLabel jLbReleaseDate;
    private javax.swing.JLabel jLbRunningTimes;
    private javax.swing.JLabel jLbTitle;
    private javax.swing.JLabel jLbTitle_creditPanel;
    private javax.swing.JLabel jLbTitle_languagePanel;
    private javax.swing.JLabel jLbTitle_locationPanel;
    private javax.swing.JLabel jLbTitle_relDatePanel;
    private javax.swing.JLabel jLbType_creditPanel;
    private javax.swing.JList<String> jListLanguages;
    private javax.swing.JList<String> jListLocations;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCreditInfo;
    private javax.swing.JPanel jPanelLanguageInfo;
    private javax.swing.JPanel jPanelLocationInfo;
    private javax.swing.JPanel jPanelReleaseDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTAreaGenres;
    private javax.swing.JTextField jTFCharacter_creditPanel;
    private javax.swing.JTextField jTFCountry_relDatePanel;
    private javax.swing.JTextField jTFDate_relDatePanel;
    private javax.swing.JTextField jTFGender_creditPanel;
    private javax.swing.JTextField jTFLanguage_languagePanel;
    private javax.swing.JTextField jTFLocation_locationPanel;
    private javax.swing.JTextField jTFName_creditPanel;
    private javax.swing.JTextField jTFPosition_creditPanel;
    private javax.swing.JTextField jTFRunningtime;
    private javax.swing.JTextField jTFTitle;
    private javax.swing.JTextField jTFType_creditPanel;
    private javax.swing.JTable jTableCredits;
    private javax.swing.JTable jTableReleaseDates;
    private javax.swing.JTextArea jTextKeywords;
    // End of variables declaration//GEN-END:variables
}
