/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.moviemanagement.GUI;

import com.mycompany.moviemanagement.Models.User;
import com.mycompany.moviemanagement.Models.UserResponse;
import com.mycompany.moviemanagement.Repositories.UserDAO;
import com.mycompany.moviemanagement.Repositories.UserDAOImp;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author nhath
 */
public class Register extends java.awt.Frame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setTitle("Register");
        jBtnSignup.setLocation(WIDTH, WIDTH);
        userDao = new UserDAOImp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLbUsername = new javax.swing.JLabel();
        jLbPwd = new javax.swing.JLabel();
        jLbRole = new javax.swing.JLabel();
        jPanelRootAuth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPwdRootAuthField = new javax.swing.JPasswordField();
        jDroplistRoles = new javax.swing.JComboBox<>();
        jUserPasswordField = new javax.swing.JPasswordField();
        jTextFieldUsername = new javax.swing.JTextField();
        jBtnSignup = new javax.swing.JButton();
        jTextPane1 = new javax.swing.JTextPane();
        jBtnLogin = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(372, 300));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Register");

        jLbUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbUsername.setText("Username:");

        jLbPwd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbPwd.setText("Password:");

        jLbRole.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLbRole.setText("Role:");

        jPanelRootAuth.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRootAuth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Root user authentication");

        jPwdRootAuthField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPwdRootAuthField.setText("jPasswordField1");

        javax.swing.GroupLayout jPanelRootAuthLayout = new javax.swing.GroupLayout(jPanelRootAuth);
        jPanelRootAuth.setLayout(jPanelRootAuthLayout);
        jPanelRootAuthLayout.setHorizontalGroup(
            jPanelRootAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootAuthLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelRootAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPwdRootAuthField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelRootAuthLayout.setVerticalGroup(
            jPanelRootAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootAuthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPwdRootAuthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jDroplistRoles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDroplistRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Client" }));
        jDroplistRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDroplistRolesActionPerformed(evt);
            }
        });

        jUserPasswordField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBtnSignup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnSignup.setText("Register");
        jBtnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignupActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextPane1.setText("Already have an account?");

        jBtnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnLogin.setText("Login");
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbPwd)
                    .addComponent(jLbUsername)
                    .addComponent(jLbRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserPasswordField)
                    .addComponent(jDroplistRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jBtnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jPanelRootAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbUsername))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbPwd)
                    .addComponent(jUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbRole, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDroplistRoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRootAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSignup)
                .addGap(18, 18, 18)
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jDroplistRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDroplistRolesActionPerformed
        // TODO add your handling code here:
        String role = jDroplistRoles.getSelectedItem().toString();
        if (role.equalsIgnoreCase("client")) {
            jPanelRootAuth.setVisible(false);
        }
        else jPanelRootAuth.setVisible(true);
    }//GEN-LAST:event_jDroplistRolesActionPerformed

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login frame = new Login();
        frame.setVisible(true);
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jBtnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignupActionPerformed
        // TODO add your handling code here:
        if(jTextFieldUsername.getText().length() < 3) {
            JOptionPane.showMessageDialog(this, "Your username must be at least 3 characters long.", "Error", ERROR_MESSAGE);
            return;
        }
        if(jUserPasswordField.getPassword().length < 8) {
            JOptionPane.showMessageDialog(this, "Your password must be at least 8 characters long.", "Error", ERROR_MESSAGE);
            return;
        }
        char[] adminKey = jPwdRootAuthField.getPassword();
        String username = jTextFieldUsername.getText();
        char[] password = jUserPasswordField.getPassword();
        String role = jDroplistRoles.getSelectedItem().toString();
        User user = new User(username, password, role);
        UserResponse res = userDao.createUser(user, adminKey);
        if(!res.success) {
            JOptionPane.showMessageDialog(this, res.errorMessage, "Error", ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, res.successMessage);
        Index index = new Index(userDao);
        index.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
                
            }
        });
    }

    UserDAO userDao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JButton jBtnSignup;
    private javax.swing.JComboBox<String> jDroplistRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbPwd;
    private javax.swing.JLabel jLbRole;
    private javax.swing.JLabel jLbUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRootAuth;
    private javax.swing.JPasswordField jPwdRootAuthField;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPasswordField jUserPasswordField;
    // End of variables declaration//GEN-END:variables
}
